apiVersion: v1
kind: Service
metadata:
  name: data-platform-masters-and-transactions-mysql-kube # リポジトリによって変更
spec:
  ports:
    - port: 3306
      nodePort: 30010
  selector:
    app: data-platform-masters-and-transactions-mysql-kube
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: data-platform-masters-and-transactions-mysql-kube # リポジトリによって変更
spec:
  selector:
    matchLabels:
      app:  data-platform-masters-and-transactions-mysql-kube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  data-platform-masters-and-transactions-mysql-kube
    spec:
      nodeName: worker
      hostname: data-platform-masters-and-transactions-mysql-kube
      containers:
        - image: mariadb:10.6
          name: data-platform-masters-and-transactions-mysql-kube
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: latona
            - name: MYSQL_PASSWORD
              value: L@ton@2020!
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: data-platform-masters-and-transactions-mysql-kube-pv-claim
        - name: initdb
          hostPath:
            path: /mnt/data-platform-masters-and-transactions-mysql-kube-init
---
# MYSQL
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-platform-masters-and-transactions-mysql-kube-pv-volume
  labels:
    type: local
  namespace: default
spec:
  storageClassName: data-platform-masters-and-transactions-mysql-kube
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-platform-masters-and-transactions-mysql-kube" # /mnt/{リポジトリ名}を指定
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-platform-masters-and-transactions-mysql-kube-pv-claim
  namespace: default
spec:
  storageClassName: data-platform-masters-and-transactions-mysql-kube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
